# Generated by Django 3.1.2 on 2021-04-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
